spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/retea_socializare_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: ${PORT:8085}

application:
  jwt:
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 7
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadasXYZ0123456789ABCDEF